name: my_new_test_app # <--- 이름을 소문자와 밑줄로 바꿨습니다!
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  supabase_flutter: ^2.10.0
  cupertino_icons: ^1.0.2
  lottie: ^3.3.1
  device_info_plus: ^11.0.0
  intl: ^0.20.2
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.3
  http: ^1.5.0
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^19.4.0
  fl_chart: ^1.0.0
  health: ^13.1.1
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  uuid: ^4.1.0
  flutter_speed_dial: ^7.0.0
  tutorial_coach_mark: ^1.2.8
  #google_mobile_ads: ^5.1.0
  google_generative_ai: ^0.4.1
  collection: any
  timezone: any
  url_launcher: ^6.3.0
  flutter_riverpod: ^2.5.1 
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  flutter_slidable: ^3.1.0 
  showcaseview: ^2.0.3
  provider: ^6.1.2
  timeago: ^3.6.1
  app_links: ^6.0.0
  audioplayers: ^6.1.0
  android_intent_plus: ^5.1.0    
  percent_indicator: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/images/home_illustration.png
    - assets/sounds/alarm_premium1.wav
    - assets/sounds/alarm_premium2.wav
    - assets/sounds/alarm_premium3.wav
    - assets/sounds/alarm_premium4.wav
    - assets/sounds/alarm_premium5.wav
    - assets/sounds/alarm_premium6.wav
    - assets/sounds/alarm_premium7.wav
    - assets/sounds/alarm_premium8.wav
    - assets/sounds/alarm_premium9.wav
dependency_overrides:
  intl: ^0.20.2
  timezone: ^0.10.0